version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - node -v  # confirm version
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Zipping application for Elastic Beanstalk..."
      - zip -r ../app.zip .
artifacts:
  files:
    - ../app.zip
