version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Zipping deployment files..."
      - zip -r app.zip ./
      - echo "Zip created. Contents:"
      - unzip -l app.zip
artifacts:
  files:
    - app.zip
