version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Zipping for Elastic Beanstalk..."
      - zip -r app.zip . -x "*.git*" "node_modules/*"
      - echo "Listing contents of app.zip..."
      - unzip -l app.zip

  files:
    - app.zip
