phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Zipping application for Elastic Beanstalk..."
      - zip -r ../app.zip .
artifacts:
  files:
    - ../app.zip
