version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Zipping files..."
      - zip -r ../app.zip .
artifacts:
  files:
    - ../app.zip
